### ISSUE TITLE
Mautic marketplace review

### ISSUE THREAD

**Issue by escopecz** [Webmecanik/mautic-bitly-bundle#1]
The plugin is written nicely, the code is clean and readable. I can see from the readme that it required Mautic 5 or higher. Please update also https://github.com/Webmecanik/mautic-bitly-bundle/blob/main/composer.json#L10 to that information including PHP 8+ as this plugin uses PHP 8 syntax and won't work on 7.4.

For my standards I'd also throw in some tests but that's so far no requirement for the marketplace so once the config.json is updated this is good to go 👍

**Comment by kuzmany** [comment]
Done

**Comment by escopecz** [comment]
As this won't work with M5 I'd also increase https://github.com/Webmecanik/mautic-bitly-bundle/blob/main/composer.json#L12

And consider also removing the upper PHP limit in https://github.com/Webmecanik/mautic-bitly-bundle/blob/main/composer.json#L11 as it would block people from testing this plugin on PHP 8.2. Not necessary. Just philosophical view on PHP version restriction. Both has pros and cons. Symfony does not have upper limit either.

**Comment by kuzmany** [comment]
@escopecz  can you check it now ? https://github.com/Webmecanik/mautic-bitly-bundle/blob/main/composer.json#L12

**Comment by escopecz** [comment]
Looks good. Thanks!
